
SELECT
  p.document_id AS id,
  JSON_VALUE(p.data, '$.name') AS name,
  e.name_kana,
  JSON_VALUE(p.data, '$.regionId') AS region_id,
  JSON_VALUE(p.data, '$.zoneId') AS zone_id,
  JSON_VALUE(p.data, '$.areaId') AS area_id,
  JSON_VALUE(p.data, '$.region') AS region_name,
  JSON_VALUE(p.data, '$.zone') AS zone_name,
  JSON_VALUE(p.data, '$.area') AS area_name,
  JSON_VALUE(p.data, '$.level') AS level,
  CAST(JSON_VALUE(p.data, '$.maxDepth') AS FLOAT64) AS max_depth,
  JSON_QUERY(p.data, '$.mainDepth') AS main_depth_json,
  JSON_VALUE(p.data, '$.entryType') AS entry_type,
  JSON_VALUE(p.data, '$.current') AS current_condition,
  JSON_QUERY(p.data, '$.topography') AS topography_json,
  JSON_QUERY(p.data, '$.features') AS features_json,
  JSON_VALUE(p.data, '$.description') AS description,
  JSON_QUERY(p.data, '$.coordinates') AS coordinates_json,
  JSON_VALUE(p.data, '$.googlePlaceId') AS google_place_id,
  JSON_VALUE(p.data, '$.formattedAddress') AS formatted_address,
  JSON_VALUE(p.data, '$.imageUrl') AS image_url,
  JSON_QUERY(p.data, '$.images') AS images_json,
  JSON_VALUE(p.data, '$.imageKeyword') AS image_keyword,
  JSON_VALUE(p.data, '$.submitterId') AS submitter_id,
  CAST(JSON_VALUE(p.data, '$.rating') AS FLOAT64) AS rating,
  CAST(JSON_VALUE(p.data, '$.reviewCount') AS INT64) AS review_count,
  CAST(JSON_VALUE(p.data, '$.bookmarkCount') AS INT64) AS bookmark_count,
  JSON_QUERY(p.data, '$.officialStats') AS official_stats_json,
  JSON_QUERY(p.data, '$.actualStats') AS actual_stats_json,
  JSON_VALUE(p.data, '$.status') AS status,
  JSON_VALUE(p.data, '$.createdAt') AS created_at
FROM `wedive_master_data_v1.points_raw_latest` p
LEFT JOIN `wedive_master_data_v1.points_enriched` e ON p.document_id = e.id
